./maestro --verbose=true \
          --print_res=false \
          --DFSL_file='data/DFSL_description/Resnet50_shi.m' \
          --full_buffer=false \
          --noc_bw=32 \
          --noc_hops=10 \
          --noc_hop_latency=1 \
          --noc_mc_support=true \
          --top_bw_only=true \
          --bw_sweep=true \
          --num_pes=65536 \
          --num_simd_lanes=1 \
          --l1_size=32 \
          --l2_size=512 \
          --do_implicit_reduction=true \
          --do_fg_sync=false \
          --do_reduction_op=true \
          --do_dse=false \
          --print_design_space=true \
          --min_num_PEs=32 \
          --min_noc_bw=8 \
          --max_num_PEs=8192 \
          --max_noc_bw=8 \
          --pe_tick=2 \
          --bw_tick=4 \
          --msg_print_lv=0 \
          --area_constraint=16000000 \
          --power_constraint=450 \
          --optimization_target=energy


./maestro --verbose=true \
          --print_res=false \
          --DFSL_file='data/DFSL_description/Resnet50_dla.m' \
          --full_buffer=false \
          --noc_bw=32 \
          --noc_hops=10 \
          --noc_hop_latency=1 \
          --noc_mc_support=true \
          --top_bw_only=true \
          --bw_sweep=true \
          --num_pes=65536 \
          --num_simd_lanes=1 \
          --l1_size=32 \
          --l2_size=512 \
          --do_implicit_reduction=true \
          --do_fg_sync=false \
          --do_reduction_op=true \
          --do_dse=false \
          --print_design_space=true \
          --min_num_PEs=32 \
          --min_noc_bw=8 \
          --max_num_PEs=8192 \
          --max_noc_bw=8 \
          --pe_tick=2 \
          --bw_tick=4 \
          --msg_print_lv=0 \
          --area_constraint=16000000 \
          --power_constraint=450 \
          --optimization_target=energy


./maestro --verbose=true \
          --print_res=false \
          --DFSL_file='data/DFSL_description/Resnet50_ws.m' \
          --full_buffer=false \
          --noc_bw=32 \
          --noc_hops=10 \
          --noc_hop_latency=1 \
          --noc_mc_support=true \
          --top_bw_only=true \
          --bw_sweep=true \
          --num_pes=65536 \
          --num_simd_lanes=1 \
          --l1_size=32 \
          --l2_size=512 \
          --do_implicit_reduction=true \
          --do_fg_sync=false \
          --do_reduction_op=true \
          --do_dse=false \
          --print_design_space=true \
          --min_num_PEs=32 \
          --min_noc_bw=8 \
          --max_num_PEs=8192 \
          --max_noc_bw=8 \
          --pe_tick=2 \
          --bw_tick=4 \
          --msg_print_lv=0 \
          --area_constraint=16000000 \
          --power_constraint=450 \
          --optimization_target=energy


./maestro --verbose=true \
          --print_res=false \
          --DFSL_file='data/DFSL_description/Resnet50_rs.m' \
          --full_buffer=false \
          --noc_bw=32 \
          --noc_hops=10 \
          --noc_hop_latency=1 \
          --noc_mc_support=true \
          --top_bw_only=true \
          --bw_sweep=true \
          --num_pes=65536 \
          --num_simd_lanes=1 \
          --l1_size=32 \
          --l2_size=512 \
          --do_implicit_reduction=true \
          --do_fg_sync=false \
          --do_reduction_op=true \
          --do_dse=false \
          --print_design_space=true \
          --min_num_PEs=32 \
          --min_noc_bw=8 \
          --max_num_PEs=8192 \
          --max_noc_bw=8 \
          --pe_tick=2 \
          --bw_tick=4 \
          --msg_print_lv=0 \
          --area_constraint=16000000 \
          --power_constraint=450 \
          --optimization_target=energy


./maestro --verbose=true \
          --print_res=false \
          --DFSL_file='data/DFSL_description/Resnet50_nlr.m' \
          --full_buffer=false \
          --noc_bw=32 \
          --noc_hops=10 \
          --noc_hop_latency=1 \
          --noc_mc_support=true \
          --top_bw_only=true \
          --bw_sweep=true \
          --num_pes=65536 \
          --num_simd_lanes=1 \
          --l1_size=32 \
          --l2_size=512 \
          --do_implicit_reduction=true \
          --do_fg_sync=false \
          --do_reduction_op=true \
          --do_dse=false \
          --print_design_space=true \
          --min_num_PEs=32 \
          --min_noc_bw=8 \
          --max_num_PEs=8192 \
          --max_noc_bw=8 \
          --pe_tick=2 \
          --bw_tick=4 \
          --msg_print_lv=0 \
          --area_constraint=16000000 \
          --power_constraint=450 \
          --optimization_target=energy




./maestro --verbose=true \
          --print_res=false \
          --DFSL_file='data/DFSL_description/UNet_shi.m' \
          --full_buffer=false \
          --noc_bw=32 \
          --noc_hops=10 \
          --noc_hop_latency=1 \
          --noc_mc_support=true \
          --top_bw_only=true \
          --bw_sweep=true \
          --num_pes=65536 \
          --num_simd_lanes=1 \
          --l1_size=32 \
          --l2_size=512 \
          --do_implicit_reduction=true \
          --do_fg_sync=false \
          --do_reduction_op=true \
          --do_dse=false \
          --print_design_space=true \
          --min_num_PEs=32 \
          --min_noc_bw=8 \
          --max_num_PEs=8192 \
          --max_noc_bw=8 \
          --pe_tick=2 \
          --bw_tick=4 \
          --msg_print_lv=0 \
          --area_constraint=16000000 \
          --power_constraint=450 \
          --optimization_target=energy


./maestro --verbose=true \
          --print_res=false \
          --DFSL_file='data/DFSL_description/UNet_DLA.m' \
          --full_buffer=false \
          --noc_bw=32 \
          --noc_hops=10 \
          --noc_hop_latency=1 \
          --noc_mc_support=true \
          --top_bw_only=true \
          --bw_sweep=true \
          --num_pes=65536 \
          --num_simd_lanes=1 \
          --l1_size=32 \
          --l2_size=512 \
          --do_implicit_reduction=true \
          --do_fg_sync=false \
          --do_reduction_op=true \
          --do_dse=false \
          --print_design_space=true \
          --min_num_PEs=32 \
          --min_noc_bw=8 \
          --max_num_PEs=8192 \
          --max_noc_bw=8 \
          --pe_tick=2 \
          --bw_tick=4 \
          --msg_print_lv=0 \
          --area_constraint=16000000 \
          --power_constraint=450 \
          --optimization_target=energy

./maestro --verbose=true \
          --print_res=false \
          --DFSL_file='data/DFSL_description/UNet_ws.m' \
          --full_buffer=false \
          --noc_bw=32 \
          --noc_hops=10 \
          --noc_hop_latency=1 \
          --noc_mc_support=true \
          --top_bw_only=true \
          --bw_sweep=true \
          --num_pes=65536 \
          --num_simd_lanes=1 \
          --l1_size=32 \
          --l2_size=512 \
          --do_implicit_reduction=true \
          --do_fg_sync=false \
          --do_reduction_op=true \
          --do_dse=false \
          --print_design_space=true \
          --min_num_PEs=32 \
          --min_noc_bw=8 \
          --max_num_PEs=8192 \
          --max_noc_bw=8 \
          --pe_tick=2 \
          --bw_tick=4 \
          --msg_print_lv=0 \
          --area_constraint=16000000 \
          --power_constraint=450 \
          --optimization_target=energy


./maestro --verbose=true \
          --print_res=false \
          --DFSL_file='data/DFSL_description/UNet_RS.m' \
          --full_buffer=false \
          --noc_bw=32 \
          --noc_hops=10 \
          --noc_hop_latency=1 \
          --noc_mc_support=true \
          --top_bw_only=true \
          --bw_sweep=true \
          --num_pes=65536 \
          --num_simd_lanes=1 \
          --l1_size=32 \
          --l2_size=512 \
          --do_implicit_reduction=true \
          --do_fg_sync=false \
          --do_reduction_op=true \
          --do_dse=false \
          --print_design_space=true \
          --min_num_PEs=32 \
          --min_noc_bw=8 \
          --max_num_PEs=8192 \
          --max_noc_bw=8 \
          --pe_tick=2 \
          --bw_tick=4 \
          --msg_print_lv=0 \
          --area_constraint=16000000 \
          --power_constraint=450 \
          --optimization_target=energy




./maestro --verbose=true \
          --print_res=false \
          --DFSL_file='data/DFSL_description/UNet_nlr.m' \
          --full_buffer=false \
          --noc_bw=32 \
          --noc_hops=10 \
          --noc_hop_latency=1 \
          --noc_mc_support=true \
          --top_bw_only=true \
          --bw_sweep=true \
          --num_pes=65536 \
          --num_simd_lanes=1 \
          --l1_size=32 \
          --l2_size=512 \
          --do_implicit_reduction=true \
          --do_fg_sync=false \
          --do_reduction_op=true \
          --do_dse=false \
          --print_design_space=true \
          --min_num_PEs=32 \
          --min_noc_bw=8 \
          --max_num_PEs=8192 \
          --max_noc_bw=8 \
          --pe_tick=2 \
          --bw_tick=4 \
          --msg_print_lv=0 \
          --area_constraint=16000000 \
          --power_constraint=450 \
          --optimization_target=energy



